export const dropdownOptions = {
  AGE_OPTIONS: [
    { key: 'under10' },
    { key: '20s30s' },
    { key: '40s50s' },
    { key: '60s_and_up' },
  ],
  NATIONALITY_OPTIONS: [
    { key: 'china' },
    { key: 'usa' },
    { key: 'turkey' },
    { key: 'thailand' },
    { key: 'other', directInput: true },
  ],
  BUSINESS_INFO_OPTIONS: [
    { key: 'selfEmployed' },
    { key: 'prospective' },
    { key: 'other', directInput: true },
  ],
  INDUSTRY_OPTIONS: [
    { key: 'restaurant' },
    { key: 'retail' },
    { key: 'service' },
    { key: 'it' },
    { key: 'culture' },
    { key: 'other', directInput: true },
  ],
  RESIDENCE_STATUS_OPTIONS: [
    { key: 'student' },
    { key: 'jobSeeker' },
    { key: 'investor' },
    { key: 'shortTerm' },
    { key: 'training' },
    { key: 'other', directInput: true },
  ],
  EXPECTED_STAY_PERIOD_OPTIONS: [
    { key: 'under3m' },
    { key: 'under6m' },
    { key: 'under1y' },
    { key: 'under2y' },
    { key: 'under3y' },
    { key: 'under5y' },
    { key: 'permanent' },
    { key: 'unknown' },
  ],
  WORK_EXPERIENCE_OPTIONS: [
    { key: 'none' },
    { key: '1y_plus' },
    { key: '2y_plus' },
    { key: '3y_plus' },
    { key: '5y_plus' },
    { key: '10y_plus' },
  ],
  DEGREE_OPTIONS: [
    { key: 'none' },
    { key: 'highSchool' },
    { key: 'associate' },
    { key: 'bachelor' },
    { key: 'master' },
    { key: 'doctorate' },
    { key: 'other', directInput: true },
  ],
  KOREAN_PROFICIENCY_OPTIONS: [
    { key: 'none' },
    { key: 'basic' },
    { key: 'intermediate' },
    { key: 'advanced' },
    { key: 'university' },
    { key: 'other', directInput: true },
  ],
  CATEGORY_OPTIONS: [
    { key: 'qna' },
    { key: 'discussion' },
    { key: 'help' },
    { key: 'tips' },
  ],
};
